# Generated by Django 3.1.2 on 2020-10-20 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('date', models.DateField()),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('Male', 'M'), ('Female', 'F')], default='Male', max_length=15)),
                ('mobile', models.CharField(max_length=15)),
                ('city', models.CharField(max_length=150)),
                ('salary_expectation', models.IntegerField()),
                ('relocate', models.BooleanField(default=0)),
            ],
        ),
    ]
